language: ruby
rvm:
- 2.2.1
script: bundle exec rake generate
deploy:
  provider: heroku
  api_key:
    secure: Hs7f4LZzQALRAjQv9OxHqN0fSEm0StSWPf4nNOYbsX+Ftk41Zi01LRtBJ/6/1Y4QM3NlTYjEpdG+e78DqSt3mtgFhVPH7wB4t1HjqwBVGQhnhdEMWShjYsy4ORkTyBrtl+2FMDaaRCHjHHkN1k+TDSwQ1r6bYCl7NbNItqRfzjc=
  app: sprestage-journey-blog
  on:
    repo: sprestage/journey-octoblog
